### PR TITLE
Restore project name in Zapier trigger

### LINKED ISSUE #24: Regression: Creator & Project fields no longer set for new tickets
We have a couple of Zaps  - One that sends a message to chat when a new ticket is created, and another that sends one when a ticket is updated.

During a previous update to the Zapier integration, we lost the "Creator" and "Project" fields for new ticket notifications; they're always blank now, including when the sample data is fetched during Zap setup:

image

I can't see any other fields that contain the same data; perhaps i'm missing something?

### PR DESCRIPTION
**Pull request by tommoor**
- Restore project name in Zapier trigger
- Add pagination to issue trigger
- Reduce pagination limit to lower complexity load

image

closes #24

### CODE REVIEW

File: src/triggers/issue.ts [hunk 1]
```diff
@@ -63,7 +74,8 @@ const buildIssueList = (orderBy: "createdAt" | "updatedAt") => async (z: ZObject
       ) {
         team(id: $teamId) {
           issues(
-            first: 25
+            first: 10
```
Comment (tommoor) [inline src/triggers/issue.ts:77]: This endpoint is polled, most of the time there won't be many issues created since the last poll so it makes sense to keep the pagination limit and complexity low.

**Review by urossmolnik — APPROVED** [review]
